### ISSUE TITLE
Issue converting Blog from R-Studio to Github Desktop

### ISSUE THREAD

**Issue by lyndsaymh** [CrumpLab/psyc73800#4]
Hello! I ran into this issue and I thought others might have run into this problem as well. 

Yesterday, I was able to create a blog in RStudio but when I went to add it to Github, I ran into an issue. I clicked on “Adding an existing repository” but when I attempted to choose the blog that I created in R-studio, it said that “This directory does not appear to be a Git repository.” I have attached an image of what that looks like. 

Any suggestions? 

Many thanks! 

Lyndsay Hage

<img width="447" alt="Screen Shot 2020-08-28 at 12 49 01 AM" src="https://user-images.githubusercontent.com/70360548/91626139-723b6b00-e97a-11ea-945e-2d784993986b.png">

**Comment by CrumpLab** [comment]
Hi Lyndsay,

Thanks for opening this issue. The message you received means that the folder where you created the blog was not initialized as a git repository. When a folder is initialized as a git repository, git creates some hidden files in the folder, and github desktop was looking for those files (and didn't find them).

To troubleshoot, a first question is whether you had the configure for github pages option clicked when you made the project?

<img width="766" alt="Screen Shot 2020-08-27 at 11 17 05 AM" src="https://user-images.githubusercontent.com/4038982/91634202-9881fa80-e9bc-11ea-99e5-63d54c4016ed.png">

This should have added the necessary hidden files to create the project folder as a git repo. However, it is also possible that you don't have git installed on your machine (it often comes preloaded, but sometimes it doesn't). If you don't already have git installed, then even if you clicked configure for github pages, you'll get this same error.

1. check if you have git on your computer (it looks like you are on a mac, so open the "terminal" program and enter these lines:

```
which git
git --version
```

When I do this, I see the following, indicating that git is installed:

<img width="506" alt="Screen Shot 2020-08-29 at 6 03 28 AM" src="https://user-images.githubusercontent.com/4038982/91634300-61f8af80-e9bd-11ea-90d6-7a0734f79339.png">

2. If git is not installed, you can go to the git website, and download the installer: 

<https://git-scm.com>

Then, repeat the above to double-check that it is installed.

3. You should now be able convert your R project folder with the blog into a git folder. Follow these steps:

  - Open the R project in R studio
  - Install the `usethis` package (packages tab, choose install, enter usethis)
  - run this command in the console:

```
usethis::use_git()
```

You should now have git installed, and your folder should now be a git repository. If it is, you will see a git tab appear in R studio (top right pane). You will also be able to add the folder to github desktop. 

Let me know if this works

**Comment by lyndsaymh** [comment]
Hello Dr. Crump,

Yes! This worked. It was step 3 that did it! The blog is working and I am preparing my first post. I'm looking forward to learning how to use this platform more. 

Again, many thanks for your assistance!

Lyndsay Hage
